name: lint
on:
  push:
    branches: master
  pull_request:
    branches: master
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: "3.x"
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6
      - run: pip install tox
      - name: Run linter
        run: tox -e lint
